// frontend/vue-template/src/views/Register.vue
<template>
  <div class="card" style="max-width: 420px">
    <h2>Register</h2>
    <form @submit.prevent="submit">
      <div style="margin-bottom: 0.75rem">
        <label>Name</label>
        <input v-model="name" required />
      </div>
      <div style="margin-bottom: 0.75rem">
        <label>Email</label>
        <input v-model="email" type="email" required autocomplete="email" />
      </div>
      <div style="margin-bottom: 0.75rem">
        <label>Password (min 8)</label>
        <input v-model="password" type="password" required minlength="8" autocomplete="new-password" />
      </div>
      <p v-if="err" class="error">{{ err }}</p>
      <button class="primary" type="submit">Create account</button>
    </form>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { api, unwrap } from '../api';

const router = useRouter();
const name = ref('');
const email = ref('');
const password = ref('');
const err = ref('');

async function submit() {
  err.value = '';
  try {
    const res = await api.post('/auth/register', {
      name: name.value,
      email: email.value,
      password: password.value,
    });
    const data = unwrap(res);
    localStorage.setItem('polystack_token', data.tokens.access_token);
    router.push('/dashboard');
  } catch (e) {
    err.value = e.message || 'Register failed';
  }
}
</script>

// frontend/angular-template/src/app/pages/register.component.ts
import { Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ApiService } from '../services/api.service';

@Component({
  standalone: true,
  imports: [ReactiveFormsModule],
  template: `
    <div class="card" style="max-width: 420px">
      <h2>Register</h2>
      <form [formGroup]="form" (ngSubmit)="submit()">
        <div style="margin-bottom: 0.75rem">
          <label>Name</label>
          <input formControlName="name" />
        </div>
        <div style="margin-bottom: 0.75rem">
          <label>Email</label>
          <input formControlName="email" type="email" autocomplete="email" />
        </div>
        <div style="margin-bottom: 0.75rem">
          <label>Password (min 8)</label>
          <input formControlName="password" type="password" minlength="8" autocomplete="new-password" />
        </div>
        @if (err) {
          <p class="error">{{ err }}</p>
        }
        <button class="primary" type="submit">Create account</button>
      </form>
    </div>
  `,
  styles: [
    `
      label {
        display: block;
        font-size: 0.85rem;
        margin-bottom: 0.25rem;
        color: #334155;
      }
      input {
        width: 100%;
        padding: 0.5rem 0.6rem;
        border-radius: 8px;
        border: 1px solid #cbd5e1;
      }
      .error {
        color: #b91c1c;
        font-size: 0.9rem;
      }
      button.primary {
        background: #2563eb;
        color: #fff;
        border: 1px solid #2563eb;
        border-radius: 8px;
        padding: 0.45rem 0.75rem;
        cursor: pointer;
      }
      .card {
        background: #fff;
        border: 1px solid #e2e8f0;
        border-radius: 10px;
        padding: 1rem 1.25rem;
      }
    `,
  ],
})
export class RegisterComponent {
  private readonly fb = inject(FormBuilder);
  private readonly api = inject(ApiService);
  private readonly router = inject(Router);

  err = '';

  form = this.fb.nonNullable.group({
    name: ['', Validators.required],
    email: ['', Validators.required],
    password: ['', [Validators.required, Validators.minLength(8)]],
  });

  submit() {
    this.err = '';
    if (this.form.invalid) return;
    this.api
      .post<{ user: unknown; tokens: { access_token: string } }>('/auth/register', this.form.getRawValue())
      .subscribe({
        next: (d) => {
          localStorage.setItem('polystack_token', d.tokens.access_token);
          this.router.navigateByUrl('/dashboard');
        },
        error: (e: Error) => {
          this.err = e.message || 'Register failed';
        },
      });
  }
}
