// frontend/vue-template/src/views/Register.vue
<template>
  <div class="card" style="max-width: 420px">
    <h2>Register</h2>
    <form @submit.prevent="submit">
      <div style="margin-bottom: 0.75rem">
        <label>Name</label>
        <input v-model="name" required />
      </div>
      <div style="margin-bottom: 0.75rem">
        <label>Email</label>
        <input v-model="email" type="email" required autocomplete="email" />
      </div>
      <div style="margin-bottom: 0.75rem">
        <label>Password (min 8)</label>
        <input v-model="password" type="password" required minlength="8" autocomplete="new-password" />
      </div>
      <p v-if="err" class="error">{{ err }}</p>
      <button class="primary" type="submit">Create account</button>
    </form>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { api, unwrap } from '../api';

const router = useRouter();
const name = ref('');
const email = ref('');
const password = ref('');
const err = ref('');

async function submit() {
  err.value = '';
  try {
    const res = await api.post('/auth/register', {
      name: name.value,
      email: email.value,
      password: password.value,
    });
    const data = unwrap(res);
    localStorage.setItem('polystack_token', data.tokens.access_token);
    router.push('/dashboard');
  } catch (e) {
    err.value = e.message || 'Register failed';
  }
}
</script>

// frontend/react-template/src/pages/Register.jsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api, unwrap } from '../api.js';

export default function Register() {
  const nav = useNavigate();
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [err, setErr] = useState('');

  async function submit(e) {
    e.preventDefault();
    setErr('');
    try {
      const res = await api.post('/auth/register', { name, email, password });
      const data = unwrap(res);
      localStorage.setItem('polystack_token', data.tokens.access_token);
      nav('/dashboard');
    } catch (e2) {
      setErr(e2.message || 'Register failed');
    }
  }

  return (
    <div className="card" style={{ maxWidth: 420 }}>
      <h2>Register</h2>
      <form onSubmit={submit}>
        <div style={{ marginBottom: '0.75rem' }}>
          <label>Name</label>
          <input value={name} onChange={(e) => setName(e.target.value)} required />
        </div>
        <div style={{ marginBottom: '0.75rem' }}>
          <label>Email</label>
          <input value={email} onChange={(e) => setEmail(e.target.value)} type="email" required autoComplete="email" />
        </div>
        <div style={{ marginBottom: '0.75rem' }}>
          <label>Password (min 8)</label>
          <input
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            type="password"
            required
            minLength={8}
            autoComplete="new-password"
          />
        </div>
        {err ? <p className="error">{err}</p> : null}
        <button className="primary" type="submit">
          Create account
        </button>
      </form>
    </div>
  );
}
