// frontend/vue-template/src/views/TaskEdit.vue
<template>
  <div class="card">
    <h2>{{ isNew ? 'New task' : 'Edit task' }}</h2>
    <form @submit.prevent="save">
      <div style="margin-bottom: 0.75rem">
        <label>Title</label>
        <input v-model="form.title" required />
      </div>
      <div style="margin-bottom: 0.75rem">
        <label>Prompt body</label>
        <textarea v-model="form.prompt_body" rows="8" required></textarea>
      </div>
      <div style="margin-bottom: 0.75rem">
        <label>Description</label>
        <textarea v-model="form.description" rows="3"></textarea>
      </div>
      <label class="row" style="gap: 0.5rem; margin-bottom: 0.75rem">
        <input v-model="form.is_reusable" type="checkbox" />
        Reusable prompt
      </label>
      <p v-if="err" class="error">{{ err }}</p>
      <button class="primary" type="submit">Save</button>
      <router-link to="/dashboard" style="margin-left: 0.5rem">Cancel</router-link>
    </form>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { api, unwrap } from '../api';

const route = useRoute();
const router = useRouter();
const isNew = computed(() => route.path.endsWith('/new'));
const err = ref('');

const form = reactive({
  title: '',
  prompt_body: '',
  description: '',
  is_reusable: true,
});

async function load() {
  if (isNew.value) return;
  const res = await api.get(`/tasks/${route.params.id}`);
  const t = unwrap(res);
  form.title = t.title;
  form.prompt_body = t.prompt_body;
  form.description = t.description || '';
  form.is_reusable = !!t.is_reusable;
}

async function save() {
  err.value = '';
  try {
    if (isNew.value) {
      const res = await api.post('/tasks', { ...form });
      const t = unwrap(res);
      router.replace(`/tasks/${t.id}`);
    } else {
      await api.put(`/tasks/${route.params.id}`, { ...form });
      router.push('/dashboard');
    }
  } catch (e) {
    err.value = e.message || 'Save failed';
  }
}

onMounted(async () => {
  try {
    await load();
  } catch (e) {
    err.value = e.message || 'Load failed';
  }
});
</script>

// frontend/react-template/src/pages/TaskEdit.jsx
import { useEffect, useMemo, useState } from 'react';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import { api, unwrap } from '../api.js';

export default function TaskEdit() {
  const { id } = useParams();
  const location = useLocation();
  const nav = useNavigate();
  const isNew = useMemo(() => location.pathname.endsWith('/tasks/new'), [location.pathname]);
  const [form, setForm] = useState({
    title: '',
    prompt_body: '',
    description: '',
    is_reusable: true,
  });
  const [err, setErr] = useState('');

  useEffect(() => {
    let cancelled = false;
    async function run() {
      if (isNew) return;
      try {
        const res = await api.get(`/tasks/${id}`);
        const t = unwrap(res);
        if (cancelled) return;
        setForm({
          title: t.title,
          prompt_body: t.prompt_body,
          description: t.description || '',
          is_reusable: !!t.is_reusable,
        });
      } catch (e) {
        if (!cancelled) setErr(e.message || 'Load failed');
      }
    }
    run();
    return () => {
      cancelled = true;
    };
  }, [id, isNew]);

  async function save(e) {
    e.preventDefault();
    setErr('');
    try {
      if (isNew) {
        const res = await api.post('/tasks', { ...form });
        const t = unwrap(res);
        nav(`/tasks/${t.id}`, { replace: true });
      } else {
        await api.put(`/tasks/${id}`, { ...form });
        nav('/dashboard');
      }
    } catch (e2) {
      setErr(e2.message || 'Save failed');
    }
  }

  return (
    <div className="card">
      <h2>{isNew ? 'New task' : 'Edit task'}</h2>
      <form onSubmit={save}>
        <div style={{ marginBottom: '0.75rem' }}>
          <label>Title</label>
          <input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required />
        </div>
        <div style={{ marginBottom: '0.75rem' }}>
          <label>Prompt body</label>
          <textarea
            rows={8}
            value={form.prompt_body}
            onChange={(e) => setForm({ ...form, prompt_body: e.target.value })}
            required
          />
        </div>
        <div style={{ marginBottom: '0.75rem' }}>
          <label>Description</label>
          <textarea rows={3} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} />
        </div>
        <label className="row" style={{ gap: '0.5rem', marginBottom: '0.75rem' }}>
          <input
            type="checkbox"
            checked={form.is_reusable}
            onChange={(e) => setForm({ ...form, is_reusable: e.target.checked })}
          />
          Reusable prompt
        </label>
        {err ? <p className="error">{err}</p> : null}
        <button className="primary" type="submit">
          Save
        </button>
        <Link to="/dashboard" style={{ marginLeft: '0.5rem' }}>
          Cancel
        </Link>
      </form>
    </div>
  );
}
